Add parameters to change pin assignment in begin function
adafruit/TinyLoRa pull request #21
Opened 2019-06-30 09:00 UTC by arjanmels

To allow this library to be used with other pin configurations I added parameters for the SPI pins.
By using default parameters, the library is still fully compatible.

Signed-off-by: Arjan Mels <arjan.mels@gmx.net>

2019-06-30 09:54 UTC, arjanmels commented
I did not realize that on original arduino SPI.begin does not take parameters. 
I guess, that makes it impossible to merge this request without compatibility issue.
Any suggestions how to work around this ina compatible way?

2019-06-30 16:27 UTC, ladyada commented
you can make it so we can pass in an &SPI object, then it can be configured however you like
https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp#L47

2019-06-30 17:32 UTC, ladyada requested changes
allow an optinal SPIdevice

2019-07-07 06:31 UTC, arjanmels commented
I close this pull request and may come back with a different one with the suggested SPI object passing.

2019-07-07 06:31 UTC, closed without merging